import re
import smtplib
import ssl
from collections import Counter
from email.message import EmailMessage
from html import escape

EMAIL_PATTERN=re.compile(r"^[^\s@]+@[^\s@]+\.[^\s@]+$")
SEVERITY_COLORS={"Critical":"#b42318","High":"#dc6803","Medium":"#b78b00","Low":"#07835d","Unknown":"#667085"}

def render_findings_html(findings,setup,intro=""):
    counts=Counter(f.severity for f in findings)
    count_text=" · ".join(f"{escape(level)}: {counts[level]}" for level in ("Critical","High","Medium","Low","Unknown") if counts[level]) or "No matching findings"
    rows=[]
    for f in findings:
        cves=", ".join(f.cves or []) or "—"; published=f.publication_date.strftime("%Y-%m-%d %H:%M UTC")
        rows.append(f'''<tr><td style="padding:10px;border-bottom:1px solid #e4edf2"><span style="background:{SEVERITY_COLORS.get(f.severity,'#667085')};color:#fff;padding:4px 8px;border-radius:999px;font-weight:700">{escape(f.severity)}</span></td><td style="padding:10px;border-bottom:1px solid #e4edf2">{escape(f.technology)}</td><td style="padding:10px;border-bottom:1px solid #e4edf2"><a style="color:#075985;font-weight:700" href="{escape(f.url,quote=True)}">{escape(f.title)}</a><div style="color:#64748b;margin-top:5px">{escape((f.summary or '')[:500])}</div></td><td style="padding:10px;border-bottom:1px solid #e4edf2">{escape(cves)}</td><td style="padding:10px;border-bottom:1px solid #e4edf2">{escape(f.source)}</td><td style="padding:10px;border-bottom:1px solid #e4edf2">{published}</td></tr>''')
    table="".join(rows) if rows else '<tr><td colspan="6" style="padding:24px;text-align:center;color:#64748b">No findings matched the current filters.</td></tr>'
    return f'''<!doctype html><html><body style="margin:0;background:#f4f8fa;font:14px Arial,sans-serif;color:#183042"><div style="max-width:1100px;margin:auto;background:#fff"><div style="padding:24px;background:#075985;color:#fff"><h1 style="margin:0 0 7px">My ThreatLens</h1><div>Security findings report · {escape(setup.name)}</div></div><div style="padding:22px"><p>{escape(intro.strip()) if intro.strip() else 'Here are the findings matching the current My ThreatLens setup and filters.'}</p><p><strong>{len(findings)} findings</strong> · {count_text}</p><table style="width:100%;border-collapse:collapse"><thead><tr style="background:#eef5f8;text-align:left"><th style="padding:10px">Severity</th><th style="padding:10px">Technology</th><th style="padding:10px">Finding</th><th style="padding:10px">CVE</th><th style="padding:10px">Source</th><th style="padding:10px">Published</th></tr></thead><tbody>{table}</tbody></table><p style="margin-top:22px;color:#64748b;font-size:12px">Generated by My ThreatLens. Verify important findings against the linked primary source and your own asset inventory.</p></div></div></body></html>'''

def send_findings_email(settings,recipient,subject,body,findings,setup):
    recipient=recipient.strip(); subject=subject.strip()
    if not EMAIL_PATTERN.fullmatch(recipient): raise ValueError("Enter a valid recipient email address.")
    if not subject or "\r" in subject or "\n" in subject: raise ValueError("Enter a valid email subject.")
    if not settings.smtp_host or not settings.smtp_from_email: raise RuntimeError("Email is not configured. Add SMTP_HOST and SMTP_FROM_EMAIL to the .env file, then restart My ThreatLens.")
    if settings.smtp_username and not settings.smtp_password: raise RuntimeError("Email authentication is incomplete. Add the Gmail app password as SMTP_PASSWORD in the .env file, then restart My ThreatLens.")
    message=EmailMessage(); message["From"]=settings.smtp_from_email; message["To"]=recipient; message["Subject"]=subject
    message.set_content((body.strip()+"\n\n" if body.strip() else "")+f"This My ThreatLens report contains {len(findings)} findings. View it in an HTML-capable email client.")
    message.add_alternative(render_findings_html(findings,setup,body),subtype="html")
    smtp_class=smtplib.SMTP_SSL if settings.smtp_use_ssl else smtplib.SMTP; kwargs={"host":settings.smtp_host,"port":settings.smtp_port,"timeout":20}
    if settings.smtp_use_ssl: kwargs["context"]=ssl.create_default_context()
    with smtp_class(**kwargs) as server:
        if settings.smtp_use_tls and not settings.smtp_use_ssl: server.starttls(context=ssl.create_default_context())
        if settings.smtp_username: server.login(settings.smtp_username,settings.smtp_password)
        server.send_message(message)
