from datetime import datetime, timezone, timedelta
ITEMS=[
{"source":"The Hacker News","title":"Microsoft Patches Record 622 Flaws, Including Two Zero-Days Under Active Attack","summary":"Microsoft security updates address actively exploited vulnerabilities across Windows and Exchange Server, including a stored XSS flaw in Outlook Web Access. Administrators should review the CVEs and apply the relevant patches.","url":"https://thehackernews.com/2026/07/microsoft-patches-record-622-flaws.html","cvss":9.6},
{"source":"The Hacker News","title":"Microsoft Confirms Active Exploitation of Windows Shell Vulnerability","summary":"Microsoft confirmed active exploitation of a Windows Shell vulnerability tracked as CVE-2026-32202 and linked it to an attack chain affecting Windows 11 and Windows Server systems.","url":"https://thehackernews.com/2026/04/microsoft-confirms-active-exploitation.html","cvss":8.8},
{"source":"The Hacker News","title":"APT28 Tied to Microsoft MSHTML Zero-Day Exploitation","summary":"APT28 exploited CVE-2026-21513, a Microsoft MSHTML security-feature bypass, as part of attacks affecting Windows 11 environments.","url":"https://thehackernews.com/2026/03/apt28-tied-to-cve-2026-21513-mshtml-0.html","cvss":8.8},
{"source":"The Hacker News","title":"On-Prem Microsoft Exchange Server Flaw Exploited via Crafted Email","summary":"Microsoft Exchange Server CVE-2026-42897 is actively exploited through crafted email opened in Outlook Web Access. The stored XSS vulnerability requires mitigation and patching.","url":"https://thehackernews.com/2026/05/on-prem-microsoft-exchange-server-cve.html","cvss":8.1,"kev":True},
{"source":"The Hacker News","title":"Palo Alto PAN-OS Flaw Under Active Exploitation Enables RCE","summary":"Palo Alto Networks PAN-OS CVE-2026-0300 is a critical remote code execution vulnerability under active exploitation. Apply the vendor mitigation and patch.","url":"https://thehackernews.com/2026/05/palo-alto-pan-os-flaw-under-active.html","cvss":9.3,"kev":True},
{"source":"The Hacker News","title":"PAN-OS RCE Exploit Under Active Use Enabling Root Access","summary":"Attackers exploit Palo Alto Networks PAN-OS CVE-2026-0300 to execute arbitrary code with root privileges.","url":"https://thehackernews.com/2026/05/pan-os-rce-exploit-under-active-use.html","cvss":9.3,"kev":True},
{"source":"The Hacker News","title":"FortiBleed Credential Theft Linked to Ransomware Operations","summary":"The FortiBleed campaign targeted FortiGate firewalls and was linked to ransomware deployment. Attackers also exploited Fortinet CVE-2026-35616.","url":"https://thehackernews.com/2026/07/fortibleed-credential-theft-linked-to.html","cvss":9.1},
{"source":"The Hacker News","title":"CISA Warns as FortiBleed Hits Thousands of FortiGate Devices","summary":"CISA warned FortiGate customers about credential attacks involving known vulnerabilities, brute force, and weak MFA protections.","url":"https://thehackernews.com/2026/06/cisa-warns-fortinet-customers-as.html","cvss":8.0},
{"source":"The Hacker News","title":"Linux Dirty Frag Privilege-Escalation Exploit Affects Major Distributions","summary":"Dirty Frag is a Linux kernel privilege escalation vulnerability affecting Ubuntu, Debian, Red Hat Enterprise Linux, Rocky Linux, and AlmaLinux systems.","url":"https://thehackernews.com/2026/05/linux-kernel-dirty-frag-lpe-exploit.html","cvss":7.8},
{"source":"The Hacker News","title":"CISA Adds Actively Exploited Linux Root Access Bug to KEV","summary":"CISA added CVE-2026-31431 to the KEV catalog. The Linux privilege escalation exploit affects Ubuntu and container environments using Docker and Kubernetes.","url":"https://thehackernews.com/2026/05/cisa-adds-actively-exploited-linux-root.html","cvss":7.8,"kev":True},
{"source":"The Hacker News","title":"Threat Actors Probe Gitea Docker Flaw After Disclosure","summary":"Threat actors probed Docker deployments for Gitea vulnerability CVE-2026-20896 shortly after public disclosure and proof-of-concept availability.","url":"https://thehackernews.com/2026/07/threat-actors-probe-gitea-docker-flaw.html","cvss":9.8},
{"source":"The Hacker News","title":"Microsoft Warns of Two Actively Exploited Defender Vulnerabilities","summary":"Microsoft Defender vulnerabilities CVE-2026-41091 and CVE-2026-45498 are actively exploited on Windows 11 and Windows Server. One enables privilege escalation and another related flaw enables RCE.","url":"https://thehackernews.com/2026/05/microsoft-warns-of-two-actively.html","cvss":7.8,"kev":True},
{"source":"BleepingComputer","title":"CISA Orders Federal Agencies to Patch Microsoft Exchange Flaw","summary":"CISA ordered agencies to mitigate the high-severity Microsoft Exchange hybrid vulnerability CVE-2025-53786. The flaw can enable privilege escalation from an on-premises Exchange server into the connected cloud environment.","url":"https://www.bleepingcomputer.com/news/security/cisa-orders-fed-agencies-to-patch-new-cve-2025-53786-exchange-flaw/","cvss":8.0},
{"source":"CISA","title":"CISA Adds FortiOS Vulnerability to Known Exploited Vulnerabilities Catalog","summary":"Fortinet FortiGate authentication bypass CVE-2024-55591 is actively exploited. Apply the vendor mitigation.","url":"https://www.cisa.gov/known-exploited-vulnerabilities-catalog?search_api_fulltext=CVE-2024-55591","kev":True},
{"source":"Microsoft MSRC","title":"Windows Security Update Addresses Critical RCE","summary":"A critical remote code execution vulnerability affects Windows 11. CVE-2025-47981.","url":"https://msrc.microsoft.com/update-guide/vulnerability/CVE-2025-47981","cvss":9.8},
{"source":"Ubuntu Security Notices","title":"Ubuntu Security Update for PostgreSQL","summary":"The Ubuntu security update fixes CVE-2025-1094 in PostgreSQL.","url":"https://ubuntu.com/security/notices/USN-7315-1","cvss":8.1},
{"source":"Cisco Security Advisories","title":"Cisco ASA and FTD VPN Web Server Remote Code Execution Vulnerability","summary":"Cisco Secure ASA and FTD VPN web servers are affected by critical CVE-2025-20333.","url":"https://sec.cloudapps.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-asaftd-webvpn-z5xP8EUB","cvss":9.9},
{"source":"Palo Alto Unit 42","title":"PAN-OS Authentication Bypass Exploit Attempts Observed","summary":"Palo Alto Networks observed exploit attempts chaining the PAN-OS authentication bypass CVE-2025-0108 with other vulnerabilities.","url":"https://security.paloaltonetworks.com/CVE-2025-0108","cvss":8.8},
]
def fixture_items(source):
    now=datetime.now(timezone.utc)
    return [{**x,"publication_date":now-timedelta(hours=i*8)} for i,x in enumerate(ITEMS) if x["source"]==source]
